# Copyright (c) 2026 Assistance Publique – Hôpitaux de Paris (AP-HP),
#                    Hôpital Henri-Mondor, and Taylor Thompson
# Licensed under the CeCILL-B Free Software License Agreement — see LICENSE.
# https://cecill.info/
"""`python -m runprov log` — read the continuous history back.

The history is ONE file, created once and appended to forever: every run this project has
ever recorded, in order, one JSON object per line. That is the same thing the predecessor's
`transformation_log.yml` was for, and the reason it is JSONL rather than YAML is that the
predecessor's file **stopped being readable**. Its writer appended `---` documents into a
file that began as a list, so `yaml.safe_load_all` raises at line 14,575 and eleven repair
scripts exist to heal it — one of which is itself a step in the pipeline it documents.

JSONL cannot fail that way. Each line stands alone: a corrupt line costs one record, never
the file, and a reader can always skip it and say so.

Because a log nobody reads is a log nobody checks, this renders it back:

    python -m runprov log                       the timeline, newest last
    python -m runprov log --format yaml         the transformation-log shape
    python -m runprov log --failed              only the runs that died
    python -m runprov log --script build_labels --limit 5
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import typing

from .project import active


def _load(path: pathlib.Path) -> tuple[list[dict[str, typing.Any]], int]:
    """Returns (records, unreadable_line_count). A bad line is COUNTED, never dropped."""
    rows, bad = [], 0
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip():
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            bad += 1
    return rows, bad


def _timeline(rows: list[dict[str, typing.Any]]) -> str:
    out = []
    for r in rows:
        status = r.get("status", "ok")
        mark = "  " if status == "ok" else "!!"
        out.append(f"{mark} {r.get('started_utc', '?'):20} {r.get('script', '?')}")
        out.append(
            f"     run_id     {r.get('run_id', '?')}   generation {r.get('generation', '?')}"
        )
        out.append(f"     command    {r.get('command', '?')}")
        if r.get("cwd"):
            out.append(f"     cwd        {r['cwd']}")
        out.append(
            f"     code       {r.get('git_commit', '?')}"
            + ("  DIRTY" if r.get("git_code_dirty") else "")
            # `is False`, never a default. A record written before this field existed does
            # not know the answer, and defaulting it to True would print the reassuring
            # answer for exactly the runs that cannot support it.
            + (
                "  DIRTY STATE UNKNOWN (git status did not run)"
                if r.get("git_status_captured") is False
                else ""
            )
        )
        ins, outs = r.get("inputs") or [], r.get("outputs") or []
        for i in ins:
            out.append(f"     in   {str(i.get('sha256') or '')[:16]}  {i.get('path', '?')}")
        for o in outs:
            out.append(f"     out  {str(o.get('sha256') or '')[:16]}  {o.get('path', '?')}")
        if status != "ok":
            f = r.get("failure") or {}
            out.append(f"     FAILED     {f.get('type', '?')}: {str(f.get('message', ''))[:160]}")
        if r.get("history_destination"):
            out.append(f"     history    {r['history_destination']}")
        if r.get("seeds"):
            out.append(f"     seeds      {r['seeds']}")
        out.append("")
    return "\n".join(out)


def _yaml(rows: list[dict[str, typing.Any]]) -> str:
    """The shape of the transformation log this replaces, generated from the real record.

    Deliberately the same field names — `step`, `input`, `output`, `script`, `run_command`,
    `date` — so anyone who reads the old file can read this one. The difference is where the
    values come from: these were observed and hashed, not typed by hand.
    """

    def q(value: object) -> str:
        """ALWAYS json.dumps. Never a cleverer rule.

        The first version quoted only when it spotted `:`, `#`, a newline or a quote — and
        emitted `cwd: ?` for a record that predates the cwd field. A bare `?` opens a YAML
        complex key, so `yaml.safe_load` died at line 10 of the rendered file. That is the
        SAME defect as the log this replaces: hand-rolled serialisation that is correct for
        the values its author happened to think of.

        JSON strings are valid YAML scalars (YAML 1.2 is a JSON superset), so quoting
        unconditionally is both simpler and total. `test_rendered_yaml_parses_with_nasty_values`
        holds the line.
        """
        return json.dumps("" if value is None else str(value))

    out = [
        "# GENERATED by `python -m runprov log --format yaml`. Do not hand-edit —",
        "# the source of truth is the append-only run history, and every path below",
        "# carries the SHA-256 that was measured when the file was read or written.",
        "",
    ]
    for r in rows:
        ins = [i.get("path", "?") for i in (r.get("inputs") or [])]
        outs = [o.get("path", "?") for o in (r.get("outputs") or [])]
        out.append(f"- step: {q(r.get('script', '?'))}")
        out.append(f"  date: {q(r.get('started_utc', '?'))}")
        out.append(f"  input: {q(', '.join(ins) or 'none registered')}")
        out.append(f"  output: {q(', '.join(outs) or 'none registered')}")
        out.append(f"  run_command: {q(r.get('command', '?'))}")
        out.append(f"  cwd: {q(r.get('cwd', '?'))}")
        out.append(f"  run_id: {q(r.get('run_id', '?'))}")
        out.append(f"  generation: {q(r.get('generation', '?'))}")
        out.append(f"  git_commit: {q(r.get('git_commit', '?'))}")
        out.append(f"  status: {q(r.get('status', 'ok'))}")
        if r.get("inputs"):
            out.append("  input_sha256:")
            for i in r["inputs"]:
                out.append(
                    "    - "
                    + q(str(i.get("sha256") or "MISSING")[:64] + "  " + str(i.get("path", "")))
                )
        if r.get("outputs"):
            out.append("  output_sha256:")
            for o in r["outputs"]:
                out.append(
                    "    - "
                    + q(str(o.get("sha256") or "MISSING")[:64] + "  " + str(o.get("path", "")))
                )
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m runprov")
    sub = ap.add_subparsers(dest="cmd", required=True)
    lg = sub.add_parser("log", help="read the continuous run history")
    lg.add_argument("--log", default=None, help="path to runs.jsonl (default: the project's)")
    lg.add_argument("--format", choices=("timeline", "yaml", "jsonl"), default="timeline")
    lg.add_argument("--limit", type=int, default=0, help="show only the last N runs")
    lg.add_argument("--script", default="", help="filter by script name")
    lg.add_argument("--run-id", default="", help="filter by run id")
    lg.add_argument("--failed", action="store_true", help="only runs that failed")
    args = ap.parse_args(argv)

    path = pathlib.Path(args.log) if args.log else active().resolved_run_log()
    if not path.is_file():
        print(
            f"no run history at {path}\n"
            f"  It is created by the first `run.write(...)`. Nothing has been recorded "
            f"here yet — which is a different thing from a run that was not recorded, "
            f"and worth telling apart.",
            file=sys.stderr,
        )
        return 1

    rows, bad = _load(path)
    total = len(rows)
    if args.script:
        rows = [r for r in rows if r.get("script") == args.script]
    if args.run_id:
        rows = [r for r in rows if r.get("run_id") == args.run_id]
    if args.failed:
        rows = [r for r in rows if r.get("status") == "failed"]
    if args.limit:
        rows = rows[-args.limit :]

    if args.format == "yaml":
        sys.stdout.write(_yaml(rows))
    elif args.format == "jsonl":
        for r in rows:
            sys.stdout.write(json.dumps(r) + "\n")
    else:
        sys.stdout.write(_timeline(rows))

    n_failed = sum(1 for r in rows if r.get("status") == "failed")
    print(
        f"# {len(rows)} of {total} run(s) from {path}"
        + (f"; {n_failed} FAILED" if n_failed else "")
        + (f"; {bad} unreadable line(s) skipped" if bad else ""),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
